######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 5 12:06:07 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += editdetails.h functions.h gamedialog.h mainwindow.h
FORMS += editdetails.ui gamedialog.ui mainwindow.ui
SOURCES += editdetails.cpp functions.cpp gamedialog.cpp main.cpp mainwindow.cpp
RESOURCES += resources.qrc
